# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
